apiVersion: samina.fu.com/v1alpha1
kind: MyTest
metadata:
  name: example-mytest
  namespace: default
spec:
  # Default values copied from <project_dir>/helm-charts/mytest/values.yaml

  # Default values for mytest.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.
  replicaCount: 1
  username: sufuf3
  containerName: mycontainer
  nameSpace: default
  image:
    repository: tensorflow/tensorflow
    tag: latest-jupyter
    pullPolicy: IfNotPresent
  nameOverride: ""
  fullnameOverride: ""
  service:
    type: NodePort
    port: 8888
    nodeport: 30567
  ingress:
    enabled: false
    annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    paths: []
    hosts:
      - chart-example.local
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
