apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mytest.fullname" . }}
  namespace: {{ .Values.nameSpace }}
  labels:
    app: {{ include "mytest.name" . }}
    app.kubernetes.io/name: {{ include "mytest.name" . }}
    helm.sh/chart: {{ include "mytest.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    samina.fu.com/username: {{ .Values.username }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "mytest.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "mytest.name" . }}
        app.kubernetes.io/name: {{ include "mytest.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.containerName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8888
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
