apiVersion: v1
kind: Service
metadata:
  name: {{ include "mytest.fullname" . }}
  namespace: {{ .Values.nameSpace }}
  labels:
    app: {{ include "mytest.name" . }}
  annotations:
    samina.fu.com/username: {{ .Values.username }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodeport }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "mytest.name" . }}
